# Generated by Django 4.1.7 on 2023-11-07 19:23

from django.db import migrations, models
import gallery_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                null=True, upload_to=gallery_app.models.artists_image_path
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="image_url",
            field=models.ImageField(
                null=True, upload_to=gallery_app.models.artworks_image_path
            ),
        ),
    ]
